"use client";

import { useMemo, useState } from "react";

type NumberFieldProps = {
  id: string;
  label: string;
  value: string;
  onChange: (value: string) => void;
  prefix?: string;
  suffix?: string;
};

function NumberField({
  id,
  label,
  value,
  onChange,
  prefix = "$",
  suffix,
}: NumberFieldProps) {
  return (
    <label htmlFor={id} className="block">
      <span className="mb-2 block text-sm font-semibold text-slate-700">
        {label}
      </span>
      <span className="flex items-center rounded-xl border border-slate-300 bg-white px-4 shadow-sm transition focus-within:border-[#1f6670] focus-within:ring-2 focus-within:ring-[#1f6670]/15">
        {prefix && <span className="text-slate-400">{prefix}</span>}
        <input
          id={id}
          type="number"
          min="0"
          step="any"
          inputMode="decimal"
          value={value}
          onChange={(event) => onChange(event.target.value)}
          className="min-w-0 flex-1 bg-transparent px-2 py-3.5 text-base text-[#10202a] outline-none"
        />
        {suffix && <span className="text-sm text-slate-400">{suffix}</span>}
      </span>
    </label>
  );
}

function toNumber(value: string) {
  const number = Number(value);
  return Number.isFinite(number) ? number : 0;
}

const currency = new Intl.NumberFormat("en-US", {
  style: "currency",
  currency: "USD",
  maximumFractionDigits: 0,
});

const decimal = new Intl.NumberFormat("en-US", {
  maximumFractionDigits: 1,
});

function Result({
  label,
  value,
  detail,
  negative = false,
}: {
  label: string;
  value: string;
  detail: string;
  negative?: boolean;
}) {
  return (
    <div className="rounded-2xl bg-[#102b36] p-6 text-white">
      <p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#d3bd87]">
        {label}
      </p>
      <p
        className={`mt-3 text-4xl font-semibold tracking-[-0.035em] ${
          negative ? "text-amber-200" : "text-white"
        }`}
      >
        {value}
      </p>
      <p className="mt-3 text-sm leading-6 text-slate-300">{detail}</p>
    </div>
  );
}

export function FinanceCalculators() {
  const [revenue, setRevenue] = useState("250000");
  const [cogs, setCogs] = useState("90000");
  const [operatingExpenses, setOperatingExpenses] = useState("125000");

  const [cash, setCash] = useState("300000");
  const [monthlyCashRevenue, setMonthlyCashRevenue] = useState("80000");
  const [monthlyCashExpenses, setMonthlyCashExpenses] = useState("110000");

  const [fixedCosts, setFixedCosts] = useState("75000");
  const [contributionMargin, setContributionMargin] = useState("60");

  const profit = useMemo(() => {
    const revenueValue = toNumber(revenue);
    const grossProfit = revenueValue - toNumber(cogs);
    const operatingProfit = grossProfit - toNumber(operatingExpenses);
    const operatingMargin =
      revenueValue > 0 ? (operatingProfit / revenueValue) * 100 : 0;

    return { grossProfit, operatingProfit, operatingMargin };
  }, [revenue, cogs, operatingExpenses]);

  const runway = useMemo(() => {
    const netBurn =
      toNumber(monthlyCashExpenses) - toNumber(monthlyCashRevenue);
    const months = netBurn > 0 ? toNumber(cash) / netBurn : null;

    return { netBurn, months };
  }, [cash, monthlyCashRevenue, monthlyCashExpenses]);

  const breakEven = useMemo(() => {
    const margin = toNumber(contributionMargin) / 100;
    return margin > 0 ? toNumber(fixedCosts) / margin : 0;
  }, [fixedCosts, contributionMargin]);

  return (
    <section className="bg-white">
      <div className="mx-auto max-w-7xl px-6 py-16 sm:px-8 md:py-24">
        <div className="grid gap-8 xl:grid-cols-3">
          <article className="flex flex-col rounded-[24px] border border-slate-200 bg-[#faf9f6] p-6 shadow-sm sm:p-8">
            <div>
              <span className="text-xs font-semibold text-[#1f6670]">01</span>
              <h2 className="mt-4 text-2xl font-semibold tracking-[-0.025em] text-[#10202a]">
                Operating profit
              </h2>
              <p className="mt-3 text-sm leading-6 text-slate-600">
                Estimate the profit generated by core operations before interest
                and taxes.
              </p>
            </div>
            <div className="mt-7 space-y-5">
              <NumberField id="revenue" label="Revenue" value={revenue} onChange={setRevenue} />
              <NumberField id="cogs" label="Cost of goods sold" value={cogs} onChange={setCogs} />
              <NumberField
                id="operating-expenses"
                label="Operating expenses"
                value={operatingExpenses}
                onChange={setOperatingExpenses}
              />
            </div>
            <div className="mt-8 space-y-3">
              <Result
                label="Operating profit"
                value={currency.format(profit.operatingProfit)}
                detail={`${decimal.format(profit.operatingMargin)}% operating margin`}
                negative={profit.operatingProfit < 0}
              />
              <p className="px-1 text-sm text-slate-500">
                Gross profit: {currency.format(profit.grossProfit)}
              </p>
            </div>
          </article>

          <article className="flex flex-col rounded-[24px] border border-slate-200 bg-[#faf9f6] p-6 shadow-sm sm:p-8">
            <div>
              <span className="text-xs font-semibold text-[#1f6670]">02</span>
              <h2 className="mt-4 text-2xl font-semibold tracking-[-0.025em] text-[#10202a]">
                Cash runway
              </h2>
              <p className="mt-3 text-sm leading-6 text-slate-600">
                Estimate how many months current cash can support the present
                monthly burn rate.
              </p>
            </div>
            <div className="mt-7 space-y-5">
              <NumberField id="cash-balance" label="Cash balance" value={cash} onChange={setCash} />
              <NumberField
                id="monthly-cash-revenue"
                label="Monthly cash inflows"
                value={monthlyCashRevenue}
                onChange={setMonthlyCashRevenue}
              />
              <NumberField
                id="monthly-cash-expenses"
                label="Monthly cash outflows"
                value={monthlyCashExpenses}
                onChange={setMonthlyCashExpenses}
              />
            </div>
            <div className="mt-8">
              <Result
                label="Estimated runway"
                value={runway.months === null ? "No burn" : `${decimal.format(runway.months)} months`}
                detail={
                  runway.netBurn > 0
                    ? `${currency.format(runway.netBurn)} net cash burn per month`
                    : `${currency.format(Math.abs(runway.netBurn))} monthly cash surplus`
                }
              />
            </div>
          </article>

          <article className="flex flex-col rounded-[24px] border border-slate-200 bg-[#faf9f6] p-6 shadow-sm sm:p-8">
            <div>
              <span className="text-xs font-semibold text-[#1f6670]">03</span>
              <h2 className="mt-4 text-2xl font-semibold tracking-[-0.025em] text-[#10202a]">
                Break-even revenue
              </h2>
              <p className="mt-3 text-sm leading-6 text-slate-600">
                Estimate the revenue required to cover fixed costs at your
                current contribution margin.
              </p>
            </div>
            <div className="mt-7 space-y-5">
              <NumberField
                id="fixed-costs"
                label="Fixed costs"
                value={fixedCosts}
                onChange={setFixedCosts}
              />
              <NumberField
                id="contribution-margin"
                label="Contribution margin"
                value={contributionMargin}
                onChange={setContributionMargin}
                prefix=""
                suffix="%"
              />
            </div>
            <div className="mt-8">
              <Result
                label="Break-even revenue"
                value={currency.format(breakEven)}
                detail={`At a ${decimal.format(toNumber(contributionMargin))}% contribution margin`}
              />
            </div>
            <p className="mt-5 text-xs leading-5 text-slate-500">
              Contribution margin equals revenue less variable costs, expressed
              as a percentage of revenue.
            </p>
          </article>
        </div>
      </div>
    </section>
  );
}
